apiVersion: apps/v1
kind: Deployment
metadata:
  name: conik-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: conik
  template:
    metadata:
      labels:
        app: conik
    spec:
      containers:
        - name: conik
          ports:
            - containerPort: 8080
          image: 285816336668.dkr.ecr.ap-northeast-2.amazonaws.com/conik-ecr:3361b154999f71e65d101a7e44c09b4af3f2151c
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15